# Generated by Django 2.0.4 on 2018-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_seats', models.PositiveSmallIntegerField()),
                ('body_type', models.CharField(max_length=50)),
                ('year_of_production', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
